name: aws-sdk-update-mocks

on:
  push:
    branches:
      - 'renovate/aws-sdk-go-monorepo'

permissions:
  contents: write
  pull-requests: read

jobs:
  go-generate:
    name: go-generate
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: '1.26.x'
      - name: generate-token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          revoke: true
      - name: download go mods
        run: |
          go mod download
      - name: go-generate
        run: |
          go generate ./...
      - name: git-commit
        run: |
          git config --global user.name 'ekristen-dev[bot]'
          git config --global user.email '169176299+ekristen-dev[bot]@users.noreply.github.com'
          git add .
          git commit -a -m 'chore: update mocks'
      - name: git-push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          branch: ${{ github.ref }}